Add code common to most existing templates
* Add userns detection.
* Set PATH to its usual default.

diff --git a/lxc-gentoo-simple b/lxc-gentoo-simple
--- a/lxc-gentoo-simple
+++ b/lxc-gentoo-simple
@@ -20,6 +20,19 @@
 # License along with this library; if not, write to the Free Software
 # Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 
+# Detect use under userns (unsupported)
+for arg in "$@"; do
+    [ "$arg" = "--" ] && break
+    if [ "$arg" = "--mapped-uid" -o "$arg" = "--mapped-gid" ]; then
+        echo "This template can't be used for unprivileged containers." 1>&2
+        echo "You may want to try the \"download\" template instead." 1>&2
+        exit 1
+    fi
+done
+
+# Make sure the usual locations are in PATH
+export PATH=$PATH:/usr/sbin:/usr/bin:/sbin:/bin
+
 DISTRO="gentoo"
 CACHE="${CACHE:-/var/cache/lxc/${DISTRO}}"
 LOCK="/var/lock/subsys/lxc.${DISTRO}"
